graph TD
  root[.well-known/home]
  root --> curies[curies]
  root --> self[self]
  root --> tmde2_auth[tmde2:auth]
  root --> tmde2_collection-feed-v2[tmde2:collection-feed-v2]
  root --> tmde2_collections[tmde2:collections]
  root --> tmde2_commerce[tmde2:commerce]
  root --> tmde2_community-profile[tmde2:community-profile]
  root --> tmde2_consent[tmde2:consent]
  root --> tmde2_cookidoo-served[tmde2:cookidoo-served]
  root --> tmde2_copilot[tmde2:copilot]
  root --> tmde2_customer-devices[tmde2:customer-devices]
  root --> tmde2_customer-recipes[tmde2:customer-recipes]
  root --> tmde2_firmware[tmde2:firmware]
  root --> tmde2_foundation[tmde2:foundation]
  root --> tmde2_foundation-tutorials[tmde2:foundation-tutorials]
  root --> tmde2_mobile-notification[tmde2:mobile-notification]
  root --> tmde2_mobile-purchases[tmde2:mobile-purchases]
  root --> tmde2_north-fork[tmde2:north-fork]
  root --> tmde2_organize[tmde2:organize]
  root --> tmde2_ownership[tmde2:ownership]
  root --> tmde2_pantry[tmde2:pantry]
  root --> tmde2_planning[tmde2:planning]
  root --> tmde2_profile[tmde2:profile]
  root --> tmde2_rating[tmde2:rating]
  root --> tmde2_reactivation[tmde2:reactivation]
  root --> tmde2_recipe-details[tmde2:recipe-details]
  root --> tmde2_recipe-feed-v2[tmde2:recipe-feed-v2]
  root --> tmde2_recipe-notes[tmde2:recipe-notes]
  root --> tmde2_recommender[tmde2:recommender]
  root --> tmde2_search[tmde2:search]
  root --> tmde2_usagebox[tmde2:usagebox]