"""Test response for cookidoo-api."""

from typing import Final

from tests.conftest import UUID

COOKIDOO_TEST_RESPONSE_AUTH_RESPONSE: Final = {
    "access_token": "eyJhbGciOiJ<redacted>",
    "expires_in": 43199,
    "id_token": "eyJhbGciOiJSUzI1Ni<redacted>",
    "iss": "https://eu.login.vorwerk.com/",
    "jti": "9f97a234-3f80-4e35-bf48-2e3e9e7e8720",
    "refresh_token": "eyJhbGciOiJSUzI1Ni<redacted>",
    "scope": "marcossapi openid profile email Online offline_access",
    "token_type": "bearer",
    "user_name": "your@email",
}

COOKIDOO_TEST_RESPONSE_USER_INFO: Final = {
    "id": UUID,
    "isPublic": False,
    "userInfo": {
        "username": "Test User",
        "description": "",
        "picture": "",
        "pictureTemplate": "",
    },
    "savedSearches": [
        {
            "id": "default",
            "search": {
                "countries": ["ch"],
                "languages": ["de"],
                "accessories": [
                    "includingFriend",
                    "includingBladeCover",
                    "includingBladeCoverWithPeeler",
                    "includingCutter",
                    "includingSensor",
                ],
            },
        }
    ],
    "foodPreferences": [],
    "meta": {
        "cloudinaryPublicId": "61c22d8465a60c86de8ca7ce045665bfa35546d78ba6f971ffbed3780d4fa026"
    },
    "thermomixes": [],
}

COOKIDOO_TEST_RESPONSE_ACTIVE_SUBSCRIPTION: Final = [
    {
        "active": True,
        "startDate": "2024-09-15T00:00:00Z",
        "expires": "2024-10-15T23:59:00Z",
        "type": "TRIAL",
        "extendedType": "TRIAL",
        "autoRenewalProduct": "Cookidoo 1 Month Free",
        "autoRenewalProductCode": None,
        "countryOfResidence": "ch",
        "subscriptionLevel": "NONE",
        "status": "RUNNING",
        "marketMismatch": False,
        "subscriptionSource": "COMMERCE",
        "_created": "2024-10-30T15:38:26.496029003Z",
        "_modified": None,
    }
]

COOKIDOO_TEST_RESPONSE_INACTIVE_SUBSCRIPTION: Final = [
    {
        "active": False,
        "startDate": "2024-09-15T00:00:00Z",
        "expires": "2024-10-15T23:59:00Z",
        "type": "TRIAL",
        "extendedType": "TRIAL",
        "autoRenewalProduct": "Cookidoo 1 Month Free",
        "autoRenewalProductCode": None,
        "countryOfResidence": "ch",
        "subscriptionLevel": "NONE",
        "status": "ENDED",
        "marketMismatch": False,
        "subscriptionSource": "COMMERCE",
        "_created": "2024-10-30T15:38:26.496029003Z",
        "_modified": None,
    }
]

COOKIDOO_TEST_RESPONSE_GET_RECIPE_DETAILS = {
    "id": "r907015",
    "tags": [
        {"id": "40-recipetag-rdpf3", "name": "Fingerfood"},
        {"id": "143-recipetag-rdpf3", "name": "Vegetarisch"},
        {"id": "166-recipetag-rdpf3", "name": "alkoholfrei"},
        {"id": "167-recipetag-rdpf3", "name": "Glutenfrei"},
        {"id": "212-marketingtag-rdpf3", "name": "Weihnachten"},
        {"id": "233-marketingtag-rdpf3", "name": "Winter"},
        {"id": "247-marketingtag-rdpf3", "name": "Geschenk"},
        {"id": "8-marketingtag-rdpf3", "name": "Europäisch"},
        {"id": "209-marketingtag-rdpf3", "name": "Herbst"},
        {"id": "230-marketingtag-rdpf3", "name": "Sommer"},
        {"id": "228-marketingtag-rdpf3", "name": "Frühling"},
        {"id": "238-marketingtag-rdpf3", "name": "Geburtstag"},
        {"id": "253-marketingtag-rdpf3", "name": "Party"},
    ],
    "times": [
        {"type": "activeTime", "comment": "", "quantity": {"value": 2700}},
        {"type": "totalTime", "comment": "", "quantity": {"value": 32400}},
    ],
    "title": "Kokos Pralinen",
    "locale": "ch",
    "status": "ok",
    "markets": ["ch"],
    "language": "de",
    "categories": [
        {
            "id": "VrkNavCategory-RPF-011",
            "title": "Desserts, Pâtisserie und Süssigkeiten",
            "subtitle": "",
            "defaultTitle": "Desserts and sweets",
        },
        {
            "id": "VrkNavCategory-RPF-020",
            "title": "Snacks",
            "subtitle": "",
            "defaultTitle": "Snacks and finger food",
        },
    ],
    "difficulty": "easy",
    "exportDate": "2024-10-28T16:08:56Z",
    "ingredients": [
        {
            "id": "com.vorwerk.ingredients.Ingredient-rpf-322",
            "title": "Kokosraspeln",
            "defaultTitle": "coconut, dried, grated, unsweetened",
            "primaryNotation": "Kokosnuss, getrocknet, geraspelt, ungesüsst",
            "shoppingCategory_ref": "com.vorwerk.categories.ShoppingCategory-rpf-6",
        },
        {
            "id": "com.vorwerk.ingredients.Ingredient-rpf-319",
            "title": "gezuckerte Kondensmilch",
            "defaultTitle": "condensed milk, sweetened",
            "primaryNotation": "gezuckerte Kondensmilch",
            "shoppingCategory_ref": "com.vorwerk.categories.ShoppingCategory-rpf-2",
        },
        {
            "id": "com.vorwerk.ingredients.Ingredient-rpf-17",
            "title": "Butter",
            "defaultTitle": "butter, unsalted (from cows' milk)",
            "primaryNotation": "Butter",
            "shoppingCategory_ref": "com.vorwerk.categories.ShoppingCategory-rpf-2",
        },
    ],
    "servingSize": {"quantity": {"value": 50}, "unitNotation": "Stück"},
    "recipeUtensils": [
        {"utensilRef": "5460-utensil-rdpf3", "utensilNotation": "Kühlschrank"}
    ],
    "categories_refs": ["VrkNavCategory-RPF-011", "VrkNavCategory-RPF-020"],
    "nutritionGroups": [
        {
            "name": "",
            "recipeNutritions": [
                {
                    "quantity": 1,
                    "nutritions": [
                        {"type": "kJ", "number": 275, "unittype": "kJ"},
                        {"type": "kcal", "number": 65.7, "unittype": "kcal"},
                        {"type": "protein", "number": 1, "unittype": "g"},
                        {"type": "carb2", "number": 5.6, "unittype": "g"},
                        {"type": "fat", "number": 4.7, "unittype": "g"},
                        {"type": "dietaryFibre", "number": 0.8, "unittype": "g"},
                    ],
                    "unitNotation": "Stück",
                }
            ],
        }
    ],
    "optionalDevices": [],
    "publicationDate": "2024-10-29T06:00:00Z",
    "targetCountries": ["ch"],
    "recipeStepGroups": [
        {
            "title": "",
            "recipeSteps": [
                {
                    "title": "1",
                    "formattedText": "<NOBR>200 g Kokosraspeln</NOBR> in den Mixtopf geben und <nobr>15 Sek./Stufe 8</nobr> zerkleinern. In eine Schüssel umfüllen und beiseitestellen.",
                },
                {
                    "title": "2",
                    "formattedText": "Kondensmilch und Butter in den Mixtopf geben und <nobr>6 Min./100°C/Stufe 2</nobr> kochen.",
                },
                {
                    "title": "3",
                    "formattedText": "Gemahlene Kokosraspeln zugeben und <nobr>2 Min./Stufe 4</nobr> vermischen. In eine Schüssel umfüllen und mindestens 8 Stunden, am besten über Nacht, in den Kühlschrank stellen.",
                },
                {
                    "title": "4",
                    "formattedText": "60 g Kokosraspeln auf einen Teller geben. Aus der Kokos-Milch-Mischung kleine Kugeln formen <NOBR>(ca. Ø 1 cm)</NOBR>, in den Kokosraspeln wälzen und bis zum Servieren kühl stellen.",
                },
            ],
        }
    ],
    "additionalDevices": [],
    "descriptiveAssets": [
        {
            "square": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/94e7404b092f239d09803fdbd4ddbac1/Derivates/ccee0755073a78a95b79d96ba26fd5e3e89c137e",
            "portrait": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/94e7404b092f239d09803fdbd4ddbac1/Derivates/ccee0755073a78a95b79d96ba26fd5e3e89c137e",
            "landscape": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/94e7404b092f239d09803fdbd4ddbac1/Derivates/ccee0755073a78a95b79d96ba26fd5e3e89c137e",
        },
        {
            "square": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/4c59187077a8767c919bd168a066c224/Derivates/dd52ed01ce418450cb05f7ef7eb9caf32d934b6f",
            "portrait": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/4c59187077a8767c919bd168a066c224/Derivates/dd52ed01ce418450cb05f7ef7eb9caf32d934b6f",
            "landscape": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/4c59187077a8767c919bd168a066c224/Derivates/dd52ed01ce418450cb05f7ef7eb9caf32d934b6f",
        },
    ],
    "thermomixVersions": ["TM5", "TM6"],
    "additionalInformation": [
        {
            "type": "VrkRecipeAdditionalInformationType",
            "content": "Die Pralinen sollen kühl aufbewahrt und gegessen werden. Sie können auch eingefroren werden.",
        }
    ],
    "recipeIngredientGroups": [
        {
            "title": "",
            "recipeIngredients": [
                {
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-322",
                    "optional": False,
                    "quantity": {"value": 260},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-322",
                    "ingredientNotation": "Kokosraspeln",
                },
                {
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-319",
                    "optional": False,
                    "quantity": {"value": 400},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-319",
                    "ingredientNotation": "gezuckerte Kondensmilch",
                },
                {
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-17",
                    "optional": False,
                    "quantity": {"value": 40},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": ", in Stücken",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-17",
                    "ingredientNotation": "Butter",
                },
            ],
        }
    ],
    "inCollections": [
        {
            "id": "col500561",
            "title": "Schneeweiss und Zuckersüss",
            "recipesCount": {"value": 6, "text": "other"},
            "market": "ch",
            "descriptiveAssets": [
                {
                    "square": "https://assets.tmecosys.com/image/upload/{transformation}/img/collection/ras/Assets/38cf56dff995c01c9a4ce2ce3b9f0bf8/Derivates/d8d563384bbd2652791aedfcb3200dde0e6221cb"
                }
            ],
        }
    ],
}

COOKIDOO_TEST_RESPONSE_GET_SHOPPING_LIST_RECIPES = {
    "recipes": [
        {
            "id": "r907016",
            "ulid": "01JBQFM448MWF37WM0CQ763MQ8",
            "title": "Mini-Pavlova mit Orangen",
            "locale": "ch",
            "status": "ok",
            "language": "de",
            "hasVariants": False,
            "isCustomerRecipe": False,
            "descriptiveAssets": [
                {
                    "square": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/1659a7ed225400e0378dfc0071fa4045/Derivates/a9a2a24272093f7aa636d4afa84d99cff10ac006",
                    "portrait": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/1659a7ed225400e0378dfc0071fa4045/Derivates/a9a2a24272093f7aa636d4afa84d99cff10ac006",
                    "landscape": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/1659a7ed225400e0378dfc0071fa4045/Derivates/a9a2a24272093f7aa636d4afa84d99cff10ac006",
                },
                {
                    "square": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/c7868b18e43639134880b2777d7fcd9f/Derivates/f7e9031db49d24e9e8e37e98618a830dda45b596",
                    "portrait": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/c7868b18e43639134880b2777d7fcd9f/Derivates/f7e9031db49d24e9e8e37e98618a830dda45b596",
                    "landscape": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/c7868b18e43639134880b2777d7fcd9f/Derivates/f7e9031db49d24e9e8e37e98618a830dda45b596",
                },
            ],
            "recipeIngredientGroups": [
                {
                    "id": "01JBQFM44769BTC1P25CNDWJK9",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-9",
                    "optional": False,
                    "quantity": {"value": 200},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-9",
                    "ingredientNotation": "Zucker",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-6",
                },
                {
                    "id": "01JBQFM447GYJYP0QR4EYSEX75",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-116",
                    "optional": False,
                    "quantity": {"value": 4},
                    "unit_ref": "",
                    "preparation": ", kalt",
                    "unitNotation": "",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-116",
                    "ingredientNotation": "Eiweisse",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-10",
                },
                {
                    "id": "01JBQFM447EDC3NKF6RZAQ9FQV",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-269",
                    "optional": False,
                    "quantity": {"value": 1},
                    "unit_ref": "65-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "Prise",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-269",
                    "ingredientNotation": "Salz",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-5",
                },
                {
                    "id": "01JBQFM44772YQA0204VFQZTG9",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-46",
                    "optional": False,
                    "quantity": {"value": 1},
                    "unit_ref": "23-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "TL",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-46",
                    "ingredientNotation": "Zitronensaft",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-9",
                },
                {
                    "id": "01JBQFM447TKG7A721C375CF0P",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-288",
                    "optional": False,
                    "quantity": {"value": 1},
                    "unit_ref": "25-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "EL",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-288",
                    "ingredientNotation": "Maizena",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-7",
                },
                {
                    "id": "01JBQFM447HKJH45AWGHHG87Q9",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-316",
                    "optional": False,
                    "quantity": {"value": 4},
                    "unit_ref": "",
                    "preparation": ", geschält, filetiert",
                    "unitNotation": "",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-316",
                    "ingredientNotation": "Orangen",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-8",
                },
                {
                    "id": "01JBQFM4476W1BN6VZBSTZ50KG",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-620",
                    "optional": False,
                    "quantity": {"value": 180},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-620",
                    "ingredientNotation": "Crème fraîche",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-2",
                },
            ],
        },
        {
            "id": "r59322",
            "ulid": "01JBQFM447FVYJP9YP0F35PNY9",
            "title": "Vollwert-Brötchen/Baguettes",
            "locale": "de",
            "status": "ok",
            "language": "de",
            "clusterId": "043293bf-82be-4548-b2c2-6bb651574c6e",
            "hasVariants": True,
            "servingSize": {"quantity": {"value": 12}, "unitNotation": "Stück"},
            "isCustomerRecipe": False,
            "descriptiveAssets": [
                {
                    "square": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/665554F6-0147-480B-9CB6-36CC5181140F/Derivates/5D3D75B4-8136-4E6A-8096-861037D5CA12",
                    "portrait": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/665554F6-0147-480B-9CB6-36CC5181140F/Derivates/5D3D75B4-8136-4E6A-8096-861037D5CA12",
                    "landscape": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/665554F6-0147-480B-9CB6-36CC5181140F/Derivates/5D3D75B4-8136-4E6A-8096-861037D5CA12",
                }
            ],
            "recipeIngredientGroups": [
                {
                    "id": "01JBQFM446FATGVE3EXT8YXSRJ",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-181",
                    "optional": False,
                    "quantity": {"value": 100},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-181",
                    "ingredientNotation": "Weizenkörner",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-7",
                    "recipeAlternativeIngredient": {
                        "localId": "com.vorwerk.ingredients.Ingredient-rpf-185",
                        "optional": False,
                        "quantity": {"value": 100},
                        "unit_ref": "11-unit-rdpf3",
                        "preparation": "",
                        "unitNotation": "g",
                        "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-185",
                        "ingredientNotation": "Dinkelkörner",
                    },
                },
                {
                    "id": "01JBQFM446JK3AW6S781AQ69NE",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-40",
                    "optional": False,
                    "quantity": {"value": 400},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-40",
                    "ingredientNotation": "Weizenmehl",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-7",
                },
                {
                    "id": "01JBQFM447X5SPZX7N1EXJAJKB",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-269",
                    "optional": False,
                    "quantity": {"value": 1.5},
                    "unit_ref": "23-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "TL",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-269",
                    "ingredientNotation": "Salz",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-5",
                },
                {
                    "id": "01JBQFM4472Z498TSDDE11C2EG",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-54",
                    "optional": False,
                    "quantity": {"value": 220},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-54",
                    "ingredientNotation": "Wasser",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-9",
                },
                {
                    "id": "01JBQFM447GRGV27DW8JZRWQNX",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-151",
                    "optional": False,
                    "quantity": {"value": 40},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-151",
                    "ingredientNotation": "Öl",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-11",
                },
                {
                    "id": "01JBQFM44709X31KCPYZ1YJ2NS",
                    "isOwned": True,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-345",
                    "optional": False,
                    "quantity": {"value": 1},
                    "unit_ref": "132-unit-rdpf3",
                    "preparation": "(40 g)",
                    "unitNotation": "Würfel",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-345",
                    "ownedTimestamp": 1730586218,
                    "ingredientNotation": "Hefe",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-10",
                },
                {
                    "id": "01JBQFM447DFBB3B109XJ82EGM",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-9",
                    "optional": False,
                    "quantity": {"value": 1},
                    "unit_ref": "65-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "Prise",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-9",
                    "ingredientNotation": "Zucker",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-6",
                },
            ],
        },
    ],
    "customerRecipes": [],
    "additionalItems": [],
}


COOKIDOO_TEST_RESPONSE_GET_INGREDIENTS = {
    "recipes": [
        {
            "id": "r907016",
            "ulid": "01JBQFM448MWF37WM0CQ763MQ8",
            "title": "Mini-Pavlova mit Orangen",
            "locale": "ch",
            "status": "ok",
            "language": "de",
            "hasVariants": False,
            "isCustomerRecipe": False,
            "descriptiveAssets": [
                {
                    "square": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/1659a7ed225400e0378dfc0071fa4045/Derivates/a9a2a24272093f7aa636d4afa84d99cff10ac006",
                    "portrait": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/1659a7ed225400e0378dfc0071fa4045/Derivates/a9a2a24272093f7aa636d4afa84d99cff10ac006",
                    "landscape": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/1659a7ed225400e0378dfc0071fa4045/Derivates/a9a2a24272093f7aa636d4afa84d99cff10ac006",
                },
                {
                    "square": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/c7868b18e43639134880b2777d7fcd9f/Derivates/f7e9031db49d24e9e8e37e98618a830dda45b596",
                    "portrait": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/c7868b18e43639134880b2777d7fcd9f/Derivates/f7e9031db49d24e9e8e37e98618a830dda45b596",
                    "landscape": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/c7868b18e43639134880b2777d7fcd9f/Derivates/f7e9031db49d24e9e8e37e98618a830dda45b596",
                },
            ],
            "recipeIngredientGroups": [
                {
                    "id": "01JBQFM44769BTC1P25CNDWJK9",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-9",
                    "optional": False,
                    "quantity": {"value": 200},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-9",
                    "ingredientNotation": "Zucker",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-6",
                },
                {
                    "id": "01JBQFM447GYJYP0QR4EYSEX75",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-116",
                    "optional": False,
                    "quantity": {"value": 4},
                    "unit_ref": "",
                    "preparation": ", kalt",
                    "unitNotation": "",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-116",
                    "ingredientNotation": "Eiweisse",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-10",
                },
                {
                    "id": "01JBQFM447EDC3NKF6RZAQ9FQV",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-269",
                    "optional": False,
                    "quantity": {"value": 1},
                    "unit_ref": "65-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "Prise",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-269",
                    "ingredientNotation": "Salz",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-5",
                },
                {
                    "id": "01JBQFM44772YQA0204VFQZTG9",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-46",
                    "optional": False,
                    "quantity": {"value": 1},
                    "unit_ref": "23-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "TL",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-46",
                    "ingredientNotation": "Zitronensaft",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-9",
                },
                {
                    "id": "01JBQFM447TKG7A721C375CF0P",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-288",
                    "optional": False,
                    "quantity": {"value": 1},
                    "unit_ref": "25-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "EL",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-288",
                    "ingredientNotation": "Maizena",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-7",
                },
                {
                    "id": "01JBQFM447HKJH45AWGHHG87Q9",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-316",
                    "optional": False,
                    "quantity": {"value": 4},
                    "unit_ref": "",
                    "preparation": ", geschält, filetiert",
                    "unitNotation": "",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-316",
                    "ingredientNotation": "Orangen",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-8",
                },
                {
                    "id": "01JBQFM4476W1BN6VZBSTZ50KG",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-620",
                    "optional": False,
                    "quantity": {"value": 180},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-620",
                    "ingredientNotation": "Crème fraîche",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-2",
                },
            ],
        },
        {
            "id": "r59322",
            "ulid": "01JBQFM447FVYJP9YP0F35PNY9",
            "title": "Vollwert-Brötchen/Baguettes",
            "locale": "de",
            "status": "ok",
            "language": "de",
            "clusterId": "043293bf-82be-4548-b2c2-6bb651574c6e",
            "hasVariants": True,
            "servingSize": {"quantity": {"value": 12}, "unitNotation": "Stück"},
            "isCustomerRecipe": False,
            "descriptiveAssets": [
                {
                    "square": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/665554F6-0147-480B-9CB6-36CC5181140F/Derivates/5D3D75B4-8136-4E6A-8096-861037D5CA12",
                    "portrait": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/665554F6-0147-480B-9CB6-36CC5181140F/Derivates/5D3D75B4-8136-4E6A-8096-861037D5CA12",
                    "landscape": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/665554F6-0147-480B-9CB6-36CC5181140F/Derivates/5D3D75B4-8136-4E6A-8096-861037D5CA12",
                }
            ],
            "recipeIngredientGroups": [
                {
                    "id": "01JBQFM446FATGVE3EXT8YXSRJ",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-181",
                    "optional": False,
                    "quantity": {"value": 100},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-181",
                    "ingredientNotation": "Weizenkörner",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-7",
                    "recipeAlternativeIngredient": {
                        "localId": "com.vorwerk.ingredients.Ingredient-rpf-185",
                        "optional": False,
                        "quantity": {"value": 100},
                        "unit_ref": "11-unit-rdpf3",
                        "preparation": "",
                        "unitNotation": "g",
                        "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-185",
                        "ingredientNotation": "Dinkelkörner",
                    },
                },
                {
                    "id": "01JBQFM446JK3AW6S781AQ69NE",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-40",
                    "optional": False,
                    "quantity": {"value": 400},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-40",
                    "ingredientNotation": "Weizenmehl",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-7",
                },
                {
                    "id": "01JBQFM447X5SPZX7N1EXJAJKB",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-269",
                    "optional": False,
                    "quantity": {"value": 1.5},
                    "unit_ref": "23-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "TL",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-269",
                    "ingredientNotation": "Salz",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-5",
                },
                {
                    "id": "01JBQFM4472Z498TSDDE11C2EG",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-54",
                    "optional": False,
                    "quantity": {"value": 220},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-54",
                    "ingredientNotation": "Wasser",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-9",
                },
                {
                    "id": "01JBQFM447GRGV27DW8JZRWQNX",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-151",
                    "optional": False,
                    "quantity": {"value": 40},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-151",
                    "ingredientNotation": "Öl",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-11",
                },
                {
                    "id": "01JBQFM44709X31KCPYZ1YJ2NS",
                    "isOwned": True,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-345",
                    "optional": False,
                    "quantity": {"value": 1},
                    "unit_ref": "132-unit-rdpf3",
                    "preparation": "(40 g)",
                    "unitNotation": "Würfel",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-345",
                    "ownedTimestamp": 1730586218,
                    "ingredientNotation": "Hefe",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-10",
                },
                {
                    "id": "01JBQFM447DFBB3B109XJ82EGM",
                    "isOwned": False,
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-9",
                    "optional": False,
                    "quantity": {"value": 1},
                    "unit_ref": "65-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "Prise",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-9",
                    "ingredientNotation": "Zucker",
                    "shoppingCategory_ref": "ShoppingCategory-rpf-6",
                },
            ],
        },
    ],
    "customerRecipes": [],
    "additionalItems": [],
}


COOKIDOO_TEST_RESPONSE_ADD_INGREDIENTS_FOR_RECIPES: Final = {
    "data": [
        {
            "id": "r59322",
            "title": "Vollwert-Brötchen/Baguettes",
            "locale": "de",
            "language": "de",
            "status": "ok",
            "ulid": "01JBQEYRFQ219DZVSFEG59AWYS",
            "clusterId": "043293bf-82be-4548-b2c2-6bb651574c6e",
            "hasVariants": True,
            "servingSize": {"quantity": {"value": 12}, "unitNotation": "Stück"},
            "descriptiveAssets": [
                {
                    "square": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/665554F6-0147-480B-9CB6-36CC5181140F/Derivates/5D3D75B4-8136-4E6A-8096-861037D5CA12",
                    "portrait": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/665554F6-0147-480B-9CB6-36CC5181140F/Derivates/5D3D75B4-8136-4E6A-8096-861037D5CA12",
                    "landscape": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/665554F6-0147-480B-9CB6-36CC5181140F/Derivates/5D3D75B4-8136-4E6A-8096-861037D5CA12",
                }
            ],
            "isCustomerRecipe": False,
            "recipeIngredientGroups": [
                {
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-181",
                    "optional": False,
                    "quantity": {"value": 100},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-181",
                    "ingredientNotation": "Weizenkörner",
                    "recipeAlternativeIngredient": {
                        "localId": "com.vorwerk.ingredients.Ingredient-rpf-185",
                        "optional": False,
                        "quantity": {"value": 100},
                        "unit_ref": "11-unit-rdpf3",
                        "preparation": "",
                        "unitNotation": "g",
                        "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-185",
                        "ingredientNotation": "Dinkelkörner",
                    },
                    "isOwned": False,
                    "shoppingCategory_ref": "ShoppingCategory-rpf-7",
                    "id": "01JBQEYRFQWG8ZQ20SMKB1JP6S",
                },
                {
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-40",
                    "optional": False,
                    "quantity": {"value": 400},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-40",
                    "ingredientNotation": "Weizenmehl",
                    "isOwned": False,
                    "shoppingCategory_ref": "ShoppingCategory-rpf-7",
                    "id": "01JBQEYRFQEVSSW39WFJVNH18Y",
                },
                {
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-269",
                    "optional": False,
                    "quantity": {"value": 1.5},
                    "unit_ref": "23-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "TL",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-269",
                    "ingredientNotation": "Salz",
                    "isOwned": False,
                    "shoppingCategory_ref": "ShoppingCategory-rpf-5",
                    "id": "01JBQEYRFQF6E7VNRPVDHMW9ET",
                },
                {
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-54",
                    "optional": False,
                    "quantity": {"value": 220},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-54",
                    "ingredientNotation": "Wasser",
                    "isOwned": False,
                    "shoppingCategory_ref": "ShoppingCategory-rpf-9",
                    "id": "01JBQEYRFQ4F96ZZ039H8868VW",
                },
                {
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-151",
                    "optional": False,
                    "quantity": {"value": 40},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-151",
                    "ingredientNotation": "Öl",
                    "isOwned": False,
                    "shoppingCategory_ref": "ShoppingCategory-rpf-11",
                    "id": "01JBQEYRFQ10JYVGWPS3E89WKR",
                },
                {
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-345",
                    "optional": False,
                    "quantity": {"value": 1},
                    "unit_ref": "132-unit-rdpf3",
                    "preparation": "(40 g)",
                    "unitNotation": "Würfel",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-345",
                    "ingredientNotation": "Hefe",
                    "isOwned": False,
                    "shoppingCategory_ref": "ShoppingCategory-rpf-10",
                    "id": "01JBQEYRFQHK543XN78Z622J92",
                },
                {
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-9",
                    "optional": False,
                    "quantity": {"value": 1},
                    "unit_ref": "65-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "Prise",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-9",
                    "ingredientNotation": "Zucker",
                    "isOwned": False,
                    "shoppingCategory_ref": "ShoppingCategory-rpf-6",
                    "id": "01JBQEYRFQRZT6XF19N3QDK16J",
                },
            ],
        },
        {
            "id": "r907016",
            "title": "Mini-Pavlova mit Orangen",
            "locale": "ch",
            "language": "de",
            "status": "ok",
            "ulid": "01JBQEYRFRD37Z0F4JB23WAAJR",
            "hasVariants": False,
            "descriptiveAssets": [
                {
                    "square": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/1659a7ed225400e0378dfc0071fa4045/Derivates/a9a2a24272093f7aa636d4afa84d99cff10ac006",
                    "portrait": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/1659a7ed225400e0378dfc0071fa4045/Derivates/a9a2a24272093f7aa636d4afa84d99cff10ac006",
                    "landscape": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/1659a7ed225400e0378dfc0071fa4045/Derivates/a9a2a24272093f7aa636d4afa84d99cff10ac006",
                },
                {
                    "square": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/c7868b18e43639134880b2777d7fcd9f/Derivates/f7e9031db49d24e9e8e37e98618a830dda45b596",
                    "portrait": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/c7868b18e43639134880b2777d7fcd9f/Derivates/f7e9031db49d24e9e8e37e98618a830dda45b596",
                    "landscape": "https://assets.tmecosys.com/image/upload/{transformation}/img/recipe/ras/Assets/c7868b18e43639134880b2777d7fcd9f/Derivates/f7e9031db49d24e9e8e37e98618a830dda45b596",
                },
            ],
            "isCustomerRecipe": False,
            "recipeIngredientGroups": [
                {
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-9",
                    "optional": False,
                    "quantity": {"value": 200},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-9",
                    "ingredientNotation": "Zucker",
                    "isOwned": False,
                    "shoppingCategory_ref": "ShoppingCategory-rpf-6",
                    "id": "01JBQEYRFQAH4W0NEC6KNPBAC9",
                },
                {
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-116",
                    "optional": False,
                    "quantity": {"value": 4},
                    "unit_ref": "",
                    "preparation": ", kalt",
                    "unitNotation": "",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-116",
                    "ingredientNotation": "Eiweisse",
                    "isOwned": False,
                    "shoppingCategory_ref": "ShoppingCategory-rpf-10",
                    "id": "01JBQEYRFQCWZWG0KY02BAMB3P",
                },
                {
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-269",
                    "optional": False,
                    "quantity": {"value": 1},
                    "unit_ref": "65-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "Prise",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-269",
                    "ingredientNotation": "Salz",
                    "isOwned": False,
                    "shoppingCategory_ref": "ShoppingCategory-rpf-5",
                    "id": "01JBQEYRFQFVEJZYT1MSQJ147H",
                },
                {
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-46",
                    "optional": False,
                    "quantity": {"value": 1},
                    "unit_ref": "23-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "TL",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-46",
                    "ingredientNotation": "Zitronensaft",
                    "isOwned": False,
                    "shoppingCategory_ref": "ShoppingCategory-rpf-9",
                    "id": "01JBQEYRFQQ39D3HZS4W6RP4D1",
                },
                {
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-288",
                    "optional": False,
                    "quantity": {"value": 1},
                    "unit_ref": "25-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "EL",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-288",
                    "ingredientNotation": "Maizena",
                    "isOwned": False,
                    "shoppingCategory_ref": "ShoppingCategory-rpf-7",
                    "id": "01JBQEYRFR908830YPYSE5NECB",
                },
                {
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-316",
                    "optional": False,
                    "quantity": {"value": 4},
                    "unit_ref": "",
                    "preparation": ", geschält, filetiert",
                    "unitNotation": "",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-316",
                    "ingredientNotation": "Orangen",
                    "isOwned": False,
                    "shoppingCategory_ref": "ShoppingCategory-rpf-8",
                    "id": "01JBQEYRFRRJKKDPJ39403ATTT",
                },
                {
                    "localId": "com.vorwerk.ingredients.Ingredient-rpf-620",
                    "optional": False,
                    "quantity": {"value": 180},
                    "unit_ref": "11-unit-rdpf3",
                    "preparation": "",
                    "unitNotation": "g",
                    "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-620",
                    "ingredientNotation": "Crème fraîche",
                    "isOwned": False,
                    "shoppingCategory_ref": "ShoppingCategory-rpf-2",
                    "id": "01JBQEYRFRJVE95ETRRZABSH57",
                },
            ],
        },
    ]
}

COOKIDOO_TEST_RESPONSE_EDIT_INGREDIENTS_OWNERSHIP = {
    "data": [
        {
            "id": "01JBQG02JQD3XPFMM5CXE51K25",
            "isOwned": True,
            "localId": "com.vorwerk.ingredients.Ingredient-rpf-345",
            "optional": False,
            "quantity": {"value": 1},
            "unit_ref": "132-unit-rdpf3",
            "preparation": "(40 g)",
            "unitNotation": "Würfel",
            "ingredient_ref": "com.vorwerk.ingredients.Ingredient-rpf-345",
            "ingredientNotation": "Hefe",
            "shoppingCategory_ref": "ShoppingCategory-rpf-10",
            "ownedTimestamp": 1730586610,
        }
    ]
}

COOKIDOO_TEST_RESPONSE_GET_ADDITIONAL_ITEMS = {
    "recipes": [],
    "customerRecipes": [],
    "additionalItems": [
        {"id": "01JBQGAG2VEJM15JWW9C7BQN5W", "name": "Fleisch", "isOwned": False},
        {
            "id": "01JBQGAG2WH9EQ9GHH7XN7NWGP",
            "name": "Vogel",
            "isOwned": True,
            "ownedTimestamp": 1730586951,
        },
    ],
}

COOKIDOO_TEST_RESPONSE_ADD_ADDITIONAL_ITEMS = {
    "data": [
        {"id": "01JBQGDMRMR7RJW1C8AWDGD6YP", "name": "Fleisch", "isOwned": False},
        {"id": "01JBQGDMRNHAM7AMCR6YKPYKJQ", "name": "Fisch", "isOwned": False},
    ]
}

COOKIDOO_TEST_RESPONSE_EDIT_ADDITIONAL_ITEMS_OWNERSHIP = {
    "data": [
        {
            "id": "01JBQGMGMY4KD9ZGTKAS6GQME0",
            "name": "Fisch",
            "isOwned": True,
            "ownedTimestamp": 1730587279,
        }
    ]
}

COOKIDOO_TEST_RESPONSE_EDIT_ADDITIONAL_ITEMS = {
    "data": [
        {
            "id": "01JBQGT72WP8Z31VCPQPT5VC6F",
            "name": "Vogel",
            "isOwned": True,
            "ownedTimestamp": 1730587466,
        }
    ]
}
